status = [
  "ci/circleci%",
  "continuous-integration/jenkins/branch",
]
pr_status = [
  "ci/circleci: check-linear",
]
required_approvals = 1
timeout_sec = 7200 # two hour timeout
cut_body_after = "---"

[committer]
name = "hyades-bors[bot]"
email = "sipb-hyades@mit.edu"
